# Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /src

# Proje dosyasını ve DLL'i kopyala
COPY Portfolio.WebUI.csproj ./
COPY ../Portfolio.DtoLayer.dll ./Portfolio.DtoLayer.dll

# Restore işlemi
RUN dotnet restore

# Kaynak kodları ve diğer gerekli dosyaları kopyala
COPY . .

# Projeyi publish et
RUN dotnet publish -c Release -o /app/out

# Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime

WORKDIR /app
EXPOSE 7006

COPY --from=build /app/out .

ENTRYPOINT ["dotnet", "Portfolio.WebUI.dll"]
