version: "3.8"
services:
  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "5000:80"
    networks:
      - app-net

  identity:
    build: ./Identity
    container_name: identity
    ports:
      - "5001:80"
    networks:
      - app-net

  api-gateway:
    build: ./ApiGateway
    container_name: gateway
    ports:
      - "5002:80"
    networks:
      - app-net

  frontend:
    build: ./Frontend
    container_name: frontend
    ports:
      - "5003:80"
    networks:
      - app-net

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    environment:
      SA_PASSWORD: "81A84y04o09e19."
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
