# 1. Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Proje dosyanızı kopyalayıp restore edin
COPY ["Backend/MyPortfolio.WebApi/MyPortfolio.WebApi.csproj", "MyBackend/"]
RUN dotnet restore "MyBackend/MyBackend.csproj"

# Kaynak kodu kopyala ve publish et
COPY . .
WORKDIR "/src/MyBackend"
RUN dotnet publish -c Release -o /app/publish

# 2. Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Servis portu
EXPOSE 5000

ENTRYPOINT ["dotnet", "MyPortfolio.WebApi.dll"]
