FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5001
COPY ..

RUN dotnet publish -c Release --property:PublishDir=/out

# Runtime image
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app
COPY --from=build-env /out .

ENTRYPOINT dotnet Identity.dll