FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["identity/identity.csproj", "identity/"]
RUN dotnet restore "identity/identity.csproj"
COPY . .
WORKDIR "/src/identity"
RUN dotnet publish "identity.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "identity.dll"]
