# 1. Build aþamasý
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Proje dosyanýzý kopyalayýp restore edin
COPY ["Identity/Identity.csproj", "Identity/"]
RUN dotnet restore "Identity/Identity.csproj"

# Kaynak kodu kopyala ve publish et
COPY . .
WORKDIR "/src/Identity"
RUN dotnet publish -c Release -o /app/publish

# 2. Runtime aþamasý
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Servis portu
EXPOSE 5001

ENTRYPOINT ["dotnet", "Identity.dll"]

