# 1. Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Proje dosyasını doğru yerden kopyala
COPY ApiGateway/Portfolio.OcelotGateway/Portfolio.OcelotGateway.csproj ./Portfolio.OcelotGateway/
WORKDIR /src/Portfolio.OcelotGateway
RUN dotnet restore

# Tüm kaynakları kopyala
COPY ApiGateway/Portfolio.OcelotGateway/. ./
RUN dotnet publish -c Release -o /app/publish

# 2. Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

EXPOSE 5002
ENTRYPOINT ["dotnet", "Portfolio.OcelotGateway.dll"]
