FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 7300

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["ocelot/ocelot.csproj", "ocelot/"]
RUN dotnet restore "ocelot/ocelot.csproj"
COPY . .
WORKDIR "/src/ocelot"
RUN dotnet publish "ocelot.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "ocelot.dll"]
