# 1. Build aşaması
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Proje dosyanızı kopyalayıp restore edin
COPY ["ApiGateway/Portfolio.OcelotGateway/Portfolio.OcelotGateway.csproj", "Gateway/"]
RUN dotnet restore "Gateway/Portfolio.OcelotGateway.csproj"

# Kaynak kodu kopyala ve publish et
COPY . .
WORKDIR "/src/Gateway"
RUN dotnet publish -c Release -o /app/publish

# 2. Runtime aşaması
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .

# Servis portu
EXPOSE 5002

ENTRYPOINT ["dotnet", "Portfolio.OcelotGateway.dll"]
