
name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Connect and Deploy to VPS
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: 185.87.253.227
        username: root
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd ~/portfolio
          git pull origin master
          docker compose down
          docker compose up -d --build
